"""added slots,enrollment table

Revision ID: 0f4c3da53c5e
Revises: cb73c4e76aaa
Create Date: 2026-05-21 17:32:36.295519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f4c3da53c5e'
down_revision: Union[str, Sequence[str], None] = 'cb73c4e76aaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slot', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slots_id'), 'slots', ['id'], unique=False)
    op.create_table('enrollment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slot_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('is_payed', sa.Boolean(), nullable=True),
    sa.Column('is_pass', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['slots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enrollment_id'), 'enrollment', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_enrollment_id'), table_name='enrollment')
    op.drop_table('enrollment')
    op.drop_index(op.f('ix_slots_id'), table_name='slots')
    op.drop_table('slots')
    # ### end Alembic commands ###
