"""added role and user_role table,removed role col from user table

Revision ID: 4718cba70bcb
Revises: 0f4c3da53c5e
Create Date: 2026-05-22 10:01:09.453162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4718cba70bcb'
down_revision: Union[str, Sequence[str], None] = '0f4c3da53c5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.alter_column('users', 'degree',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'passing_year',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('users', 'passing_year',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'degree',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_table('user_roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
