"""added passed at col to enrollment table

Revision ID: fa184fc73036
Revises: 4718cba70bcb
Create Date: 2026-05-26 10:59:31.250855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa184fc73036'
down_revision: Union[str, Sequence[str], None] = '4718cba70bcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrollment', sa.Column('passed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enrollment', 'passed_at')
    # ### end Alembic commands ###
